import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-angular-cli',
  templateUrl: './angular-cli.component.html',
  styleUrls: ['./angular-cli.component.css']
})
export class AngularCliComponent implements OnInit {
  public title: string;
  public description: string;

  constructor() {
    this.title = "Angular CLI";
    this.description = "A component generated by Angular CLI";
  }

  ngOnInit() {
  }

}
